import React, { useState, useEffect } from 'react';
import { 
  ResponsiveContainer, 
  RadarChart, 
  PolarGrid, 
  PolarAngleAxis, 
  PolarRadiusAxis, 
  Radar, 
  Legend,
  Tooltip,
  BarChart,
  Bar,
  XAxis,
  YAxis
} from 'recharts';
import { jsPDF } from "jspdf";
import { Icons } from './Icons';
import { AnalysisResult, AppView, UserProfile } from '../types';

interface DashboardProps {
  data: AnalysisResult;
  userProfile: UserProfile;
  setView: (view: AppView) => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ data, userProfile, setView }) => {
  const [roadmapProgress, setRoadmapProgress] = useState(0);

  useEffect(() => {
    // Animate progress bar on mount
    const timer = setTimeout(() => {
      setRoadmapProgress(15); // Simulate initial progress (Phase 1 started)
    }, 500);
    return () => clearTimeout(timer);
  }, []);

  const radarData = data.skillsAnalysis.skillMatrix.map(s => ({
    subject: s.skill,
    A: s.level,
    fullMark: 100,
  }));

  const careerData = data.careerMatches.map(c => ({
    name: c.title.split(' ')[0] + '...', // truncate for chart
    match: c.matchPercentage
  }));

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = 20;

    // --- Header Section ---
    
    // Name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(37, 99, 235); // Blue 600
    doc.text(userProfile.name.toUpperCase(), pageWidth / 2, y, { align: "center" });
    y += 10;

    // Contact Info
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    const contactText = `${userProfile.email}  |  Generated by CareerPilot AI`;
    doc.text(contactText, pageWidth / 2, y, { align: "center" });
    y += 8;

    // Divider Line
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // --- Profile Summary & Body (from AI) ---
    doc.setFontSize(11);
    doc.setTextColor(0);
    
    // Helper to add sections
    const addSection = (title: string, content: string) => {
        // Check for page break
        if (y > 270) {
            doc.addPage();
            y = 20;
        }

        // Section Title
        if (title) {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(12);
            doc.setTextColor(37, 99, 235); // Blue
            doc.text(title.toUpperCase(), margin, y);
            y += 6;
        }

        // Content
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(0);
        
        const splitText = doc.splitTextToSize(content, contentWidth);
        splitText.forEach((line: string) => {
            if (y > 280) {
                doc.addPage();
                y = 20;
            }
            doc.text(line, margin, y);
            y += 6;
        });
        y += 4; // Extra spacing after section
    };

    // We rely on the AI's "optimizedResume" for the main body (Summary, Experience, Projects, etc.)
    // The prompt asks AI to exclude Name/Email header, so we just dump the body here.
    const bodyContent = data.optimizedResume || "Resume content generating...";
    const splitBody = doc.splitTextToSize(bodyContent, contentWidth);
    
    splitBody.forEach((line: string) => {
        // Simple heuristic to detect headers in plain text to style them (optional but nice)
        const isHeader = line.trim().length < 40 && (line.includes("Summary") || line.includes("Experience") || line.includes("Education") || line.includes("Skills"));
        
        if (y > 280) {
            doc.addPage();
            y = 20;
        }

        if (isHeader) {
             y += 2;
             doc.setFont("helvetica", "bold");
             doc.setTextColor(37, 99, 235);
             doc.text(line, margin, y);
             doc.setFont("helvetica", "normal");
             doc.setTextColor(0);
        } else {
             doc.text(line, margin, y);
        }
        y += 6;
    });

    // --- Footer ---
    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 290, { align: "right" });
    }

    doc.save(`${userProfile.name.replace(/\s+/g, '_')}_Resume.pdf`);
  };

  return (
    <div className="pt-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto pb-20">
      
      {/* Welcome Banner */}
      <div className="mb-10 animate-fade-in-down">
        <h1 className="text-3xl font-bold text-white mb-2">Mission Control</h1>
        <p className="text-gray-400">Your personalized career intelligence dashboard is ready.</p>
      </div>

      {/* Top Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-10">
        <div className="glass-card p-6 rounded-2xl border-l-4 border-blue-500 animate-fade-in">
            <div className="flex justify-between items-start mb-2">
                <span className="text-gray-400 text-sm">Resume Score</span>
                <Icons.Resume className="w-5 h-5 text-blue-400" />
            </div>
            <div className="text-4xl font-bold text-white mb-1">{data.resumeFeedback.score}</div>
            <div className="text-xs text-blue-300">/ 100 ATS Ready</div>
        </div>

        <div className="glass-card p-6 rounded-2xl border-l-4 border-purple-500 animate-fade-in delay-100">
             <div className="flex justify-between items-start mb-2">
                <span className="text-gray-400 text-sm">Top Match</span>
                <Icons.Target className="w-5 h-5 text-purple-400" />
            </div>
            <div className="text-xl font-bold text-white mb-1 truncate">{data.careerMatches[0]?.title}</div>
            <div className="text-xs text-purple-300">{data.careerMatches[0]?.matchPercentage}% Compatibility</div>
        </div>

         <div className="glass-card p-6 rounded-2xl border-l-4 border-emerald-500 animate-fade-in delay-200">
             <div className="flex justify-between items-start mb-2">
                <span className="text-gray-400 text-sm">Skill Gap</span>
                <Icons.Chart className="w-5 h-5 text-emerald-400" />
            </div>
            <div className="text-xl font-bold text-white mb-1 truncate">{data.skillsAnalysis.weaknesses[0]}</div>
            <div className="text-xs text-emerald-300">Primary area to improve</div>
        </div>

        <div className="glass-card p-6 rounded-2xl border-l-4 border-pink-500 cursor-pointer hover:bg-pink-500/10 transition-colors animate-fade-in delay-300" onClick={() => setView(AppView.PRICING)}>
             <div className="flex justify-between items-start mb-2">
                <span className="text-gray-400 text-sm">Plan Status</span>
                <Icons.Zap className="w-5 h-5 text-pink-400" />
            </div>
            <div className="text-xl font-bold text-white mb-1">Free Tier</div>
            <div className="text-xs text-pink-300">Upgrade for more insights</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
        {/* Skills Radar Chart */}
        <div className="glass-card p-6 rounded-2xl lg:col-span-1 min-h-[400px]">
          <h3 className="text-lg font-bold text-white mb-6 flex items-center">
            <Icons.Brain className="mr-2 text-blue-400 w-5 h-5" /> Skill Matrix
          </h3>
          <div className="h-[300px] w-full flex items-center justify-center">
             <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="80%" data={radarData}>
                  <PolarGrid stroke="#334155" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                  <Radar
                    name="Skill Level"
                    dataKey="A"
                    stroke="#8b5cf6"
                    strokeWidth={2}
                    fill="#8b5cf6"
                    fillOpacity={0.3}
                  />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', color: '#f8fafc' }}
                  />
                </RadarChart>
             </ResponsiveContainer>
          </div>
        </div>

        {/* Career Matches */}
        <div className="glass-card p-6 rounded-2xl lg:col-span-2">
           <h3 className="text-lg font-bold text-white mb-6 flex items-center">
            <Icons.Briefcase className="mr-2 text-purple-400 w-5 h-5" /> Top Career Fits
          </h3>
          <div className="space-y-4">
            {data.careerMatches.map((career, idx) => (
                <div key={idx} className="bg-slate-800/50 p-4 rounded-xl flex flex-col md:flex-row md:items-center justify-between hover:bg-slate-800 transition-colors">
                    <div className="flex-1">
                        <div className="flex items-center">
                             <h4 className="font-bold text-white text-lg mr-3">{career.title}</h4>
                             <span className={`px-2 py-0.5 rounded text-xs font-bold ${career.demandLevel === 'High' ? 'bg-green-500/20 text-green-400' : 'bg-yellow-500/20 text-yellow-400'}`}>
                                {career.demandLevel} Demand
                             </span>
                        </div>
                        <p className="text-gray-400 text-sm mt-1">{career.description}</p>
                        <div className="mt-2 text-sm text-blue-300 font-mono">
                            {career.salaryRange}
                        </div>
                    </div>
                    <div className="mt-4 md:mt-0 md:ml-6 flex items-center">
                        <div className="text-right mr-4">
                            <div className="text-2xl font-bold text-purple-400">{career.matchPercentage}%</div>
                            <div className="text-xs text-gray-500">Match</div>
                        </div>
                        <button className="p-2 rounded-lg bg-white/5 hover:bg-white/10 text-white transition-colors">
                            <Icons.ArrowRight className="w-5 h-5" />
                        </button>
                    </div>
                </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Roadmap */}
        <div className="glass-card p-6 rounded-2xl">
            <div className="flex justify-between items-center mb-6">
                <h3 className="text-lg font-bold text-white flex items-center">
                    <Icons.Rocket className="mr-2 text-pink-400 w-5 h-5" /> Personalized Roadmap
                </h3>
                <span className="text-xs font-mono text-pink-300 bg-pink-500/10 px-2 py-1 rounded border border-pink-500/20">
                    Phase 1: Initiation
                </span>
            </div>

            {/* Animated Progress Bar */}
            <div className="mb-8">
                <div className="flex justify-between text-xs font-medium text-gray-400 mb-2">
                    <span>Journey Completion</span>
                    <span className="text-pink-400">{roadmapProgress}%</span>
                </div>
                <div className="h-2 bg-slate-700/50 rounded-full overflow-hidden backdrop-blur-sm border border-white/5">
                    <div 
                        className="h-full bg-gradient-to-r from-pink-600 to-purple-600 shadow-[0_0_10px_rgba(236,72,153,0.5)] transition-all duration-1000 ease-out relative"
                        style={{ width: `${roadmapProgress}%` }}
                    >
                        <div className="absolute right-0 top-0 bottom-0 w-0.5 bg-white/50 shadow-[0_0_10px_rgba(255,255,255,0.8)]"></div>
                    </div>
                </div>
            </div>

            <div className="space-y-6">
                {data.roadmap.map((step, idx) => (
                    <div key={idx} className="relative pl-8 border-l border-slate-700 last:border-0 pb-6 last:pb-0">
                        <div className="absolute -left-1.5 top-0 w-3 h-3 rounded-full bg-pink-500 shadow-[0_0_8px_rgba(236,72,153,0.6)]"></div>
                        <div className="mb-1 text-sm text-pink-400 font-mono">{step.duration}</div>
                        <h4 className="text-lg font-bold text-white mb-2">{step.phase}</h4>
                        <ul className="space-y-2">
                            {step.tasks.map((task, tIdx) => (
                                <li key={tIdx} className="flex items-start text-sm text-gray-400 group">
                                    <Icons.Check className="w-4 h-4 mr-2 text-slate-500 mt-0.5 flex-shrink-0 group-hover:text-pink-400 transition-colors" />
                                    {task}
                                </li>
                            ))}
                        </ul>
                    </div>
                ))}
            </div>
        </div>

        {/* Resume Analysis */}
        <div className="glass-card p-6 rounded-2xl">
            <h3 className="text-lg font-bold text-white mb-6 flex items-center">
                <Icons.Resume className="mr-2 text-orange-400 w-5 h-5" /> Resume Intelligence
            </h3>
            
            <div className="mb-6">
                <h4 className="text-sm font-bold text-gray-300 mb-2">Strengths Detected</h4>
                <div className="flex flex-wrap gap-2">
                    {data.resumeFeedback.strengths.map((s, i) => (
                        <span key={i} className="px-3 py-1 rounded-full bg-green-500/10 text-green-400 text-xs border border-green-500/20">
                            {s}
                        </span>
                    ))}
                </div>
            </div>

            <div className="mb-6">
                <h4 className="text-sm font-bold text-gray-300 mb-2">Critical Improvements</h4>
                <ul className="space-y-3">
                    {data.resumeFeedback.improvements.map((item, i) => (
                        <li key={i} className="flex items-start bg-red-500/5 p-3 rounded-lg border border-red-500/10">
                             <Icons.Zap className="w-4 h-4 mr-2 text-red-400 mt-0.5 flex-shrink-0" />
                             <span className="text-sm text-gray-300">{item}</span>
                        </li>
                    ))}
                </ul>
            </div>
            
             <button 
                onClick={handleDownloadPDF}
                className="w-full py-3 rounded-xl bg-gradient-to-r from-orange-500 to-red-500 text-white font-bold text-sm shadow-lg shadow-orange-500/20 hover:opacity-90 transition-opacity flex justify-center items-center"
             >
                <Icons.Upload className="w-4 h-4 mr-2 rotate-180" />
                Download Professional PDF
            </button>
        </div>
      </div>

    </div>
  );
};